name: Update requirements.txt

on:
  push:
    paths:
      - 'pyproject.toml'

permissions:
  contents: write

jobs:
  compile-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Compile requirements.txt
    #   https://docs.astral.sh/uv/pip/compile/#locking-requirements for options
        run: pipx run uv pip compile pyproject.toml --all-extras -o requirements.txt

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add requirements.txt
          git diff --cached --quiet || git commit -m "chore: regenerate requirements.txt"
          git push